import ts from 'typescript';
import { readFileSync } from 'node:fs';
import { DatabaseSync } from 'node:sqlite';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const sql = new DatabaseSync(':memory:');
sql.exec(readFileSync('drizzle/0000_even_ricochet.sql', 'utf8'));
const wrap = (query, args = []) => ({ bind(...values) { return wrap(query, values); }, async first() { return sql.prepare(query).get(...args) || null; }, async all() { return { results: sql.prepare(query).all(...args) }; }, async run() { const r = sql.prepare(query).run(...args); return { meta: { changes: Number(r.changes) } }; } });
const DB = { prepare: wrap, async batch(statements) { sql.exec('BEGIN'); try {
        const results = [];
        for (const s of statements)
            results.push(await s.run());
        sql.exec('COMMIT');
        return results;
    }
    catch (e) {
        sql.exec('ROLLBACK');
        throw e;
    } } };
const jar = new Map();
let platform = true;
function compile(file, deps) { const exports = {}; const code = ts.transpileModule(readFileSync(file, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText; vm.runInNewContext(code, { exports, require: name => deps[name], crypto, TextEncoder, Response, Request, URL, File, FormData, Blob, console, Date, JSON }); return exports; }
const model = compile('lib/model.ts', {});
const blobs = new Map();
const BUCKET = { async put(key, bytes, metadata) { blobs.set(key, { bytes, metadata }); }, async get(key) { const o = blobs.get(key); return o ? { body: o.bytes, httpMetadata: o.metadata.httpMetadata } : null; }, async delete(key) { blobs.delete(key); } };
const shared = { 'cloudflare:workers': { env: { DB, BUCKET } }, 'next/headers': { cookies: async () => ({ get: k => jar.has(k) ? { value: jar.get(k) } : undefined, set: (k, v) => jar.set(k, v), delete: k => jar.delete(k) }) }, '@/app/chatgpt-auth': { getChatGPTUser: async () => platform ? { userId: 'private-owner' } : null }, '@/lib/model': model };
shared['@/lib/server-auth'] = compile('lib/server-auth.ts', shared);
shared['@/lib/patient-consent'] = compile('lib/patient-consent.ts', {});
const api = compile('app/api/crm/route.ts', shared);
const logoApi = compile('app/api/branch-logo/route.ts', shared);
async function post(action, data = {}, expected = 200, origin = 'https://crm.test') { const r = await api.POST(new Request('https://crm.test/api/crm', { method: 'POST', headers: { origin, 'Content-Type': 'application/json' }, body: JSON.stringify({ action, data }) })); const result = await r.json(); assert.equal(r.status, expected, JSON.stringify(result)); return result; }
async function get() { const r = await api.GET(); return r.json(); }
const password = 'Test-only-secret-2026';
await post('setup', { username: 'owner', name: 'Owner', password });
assert.equal((await get()).user.role, 'desarrollador');
await post('setup', { username: 'another', name: 'Another', password }, 409);
await post('save', { kind: 'branches', name: 'Sucursal 2' });
let data = await get();
const branch2 = data.state.branches.find(b => b.id !== 'central').id;
await post('save', {kind:'patients', name:'Temporal', branchId:'central'});
let temporary = (await get()).state.patients.find(p=>p.name==='Temporal');
await post('save', {...temporary, kind:'patients', name:'Temporal editado'});
temporary = (await get()).state.patients.find(p=>p.id===temporary.id);
assert.equal(temporary.name, 'Temporal editado');
await post('delete', {...temporary, kind:'patients'});
assert.ok(!(await get()).state.patients.some(p=>p.id===temporary.id));
await post('save', { kind: 'patients', name: 'Paciente prueba', rut: '11111111-1', branchId: 'central' });
data = await get();
const patient = data.state.patients[0].id;
await post('save', { kind: 'patients', name: 'Duplicado', rut: '11.111.111-1', branchId: 'central' }, 400);
await post('save', { kind: 'patients', name: 'Paciente privado', rut: '22222222-2', branchId: branch2 });
await post('save', { kind: 'products', name: 'Lente prueba', sku: 'L1', barcode: '780000000001', price: 10000, stock: 2, minStock: 1, branchId: 'central' });
await post('save', { kind: 'products', name: 'Lente con abono', sku: 'L2', price: 10000, stock: 1, minStock: 1, branchId: 'central' });
data = await get();
const product = data.state.products[0].id;
assert.equal(data.state.products[0].barcode,'780000000001');
await post('save',{kind:'products',name:'Duplicado',sku:'780000000001',price:1,stock:1,minStock:0,branchId:'central'},400);
const productWithDeposit = data.state.products.find(p => p.sku === 'L2').id;
await post('user', { username: 'tech', name: 'Tecnólogo', role: 'tecnologo', branches: ['central'], permissions: model.defaults.tecnologo, password });
await post('user', { username: 'seller', name: 'Vendedor', role: 'vendedor', branches: ['central'], permissions: model.defaults.vendedor, password });
await post('user', { username: 'mount', name: 'Montajista', role: 'montajista', branches: ['central', branch2], permissions: model.defaults.montajista, password });
data = await get();
const provider = data.users.find(u => u.username === 'tech').id;
await post('save', { kind: 'schedules', branchId: 'central', providerId: provider, type: 'weekly', weekday: 4, start: '09:00', end: '18:00', available: true });
await post('save', { kind: 'appointments', branchId: 'central', patientId: patient, providerId: provider, date: '2026-10-01', time: '10:00', duration: 30, reason: 'Examen' });
await post('save', { kind: 'appointments', branchId: 'central', patientId: patient, providerId: provider, date: '2026-10-01', time: '10:15', duration: 30, reason: 'Conflicto' }, 400);
await post('save', { kind: 'clinical', branchId: 'central', patientId: patient, date: '2026-10-01', reason: 'Atención', history: 'DATOS CLINICOS PRIVADOS', od: '-1.00', oi: '-0.75', add: '+1.00', dp: '62', previousPrescription: 'OD -0.50 / OI -0.25', visualAcuityOD: '20/20', visualAcuityOI: '20/25', lensometry:'OD -1.00', followUpNotes:'Revisar adaptación', observations: 'Observación de prueba', age: 38 });
await post('save', { kind: 'jobs', branchId: 'central', patientId: patient, description: 'Montaje de lentes', status: 'Recibido' });
await post('delete', { kind: 'patients', id: patient }, 400);
await post('save', { kind: 'patients', id: patient, branchId: branch2, name: 'Paciente prueba' }, 400);
await post('logout');
await post('login', { username: 'seller', password });
data = await get();
assert.equal(data.state.clinical.length, 0);
assert.equal(data.state.patients.length, 1);
assert.equal(JSON.stringify(data).includes('DATOS CLINICOS'), false);
await post('save', { kind: 'clinical', branchId: 'central', patientId: patient, reason: 'Prohibido' }, 403);
await post('user', { username: 'hacker' }, 403);
await post('save', { kind: 'patients', branchId: branch2, name: 'Prohibido' }, 403);
await post('save', { kind: 'patients', branchId: 'central', name: 'CSRF' }, 403, 'https://evil.test');
const sale = { kind: 'sales', branchId: 'central', key: 'sale-1', lines: [{ id: product, qty: 1 }], discount: 0, method: 'Efectivo', received: 15000, patientId: patient };
const paid = await post('save', sale);
assert.equal(paid.sale.change, 5000);
assert.equal((await get()).state.products[0].stock, 1);
await post('save', sale);
assert.equal((await get()).state.products[0].stock, 1);
assert.equal((await get()).state.sales.length, 1);
const partial = await post('save', { kind: 'sales', branchId: 'central', key: 'sale-deposit', lines: [{ id: productWithDeposit, qty: 1 }], discountType: 'percent', discountRate: 10, method: 'Tarjeta', paid: 3000, patientId: patient });
assert.equal(partial.sale.discount, 1000);
assert.equal(partial.sale.total, 9000);
assert.equal(partial.sale.paid, 3000);
assert.equal(partial.sale.balance, 6000);
assert.equal(partial.sale.status, 'Abono pendiente');
const firstDeposit = await post('payment', { kind: 'sales', branchId: 'central', saleId: partial.sale.id, key: 'deposit-1', amount: 1000, method: 'Transferencia' });
assert.equal(firstDeposit.sale.paid, 4000);
assert.equal(firstDeposit.sale.balance, 5000);
assert.equal(firstDeposit.sale.payments.length, 2);
const duplicateDeposit = await post('payment', { kind: 'sales', branchId: 'central', saleId: partial.sale.id, key: 'deposit-1', amount: 1000, method: 'Transferencia' });
assert.equal(duplicateDeposit.sale.balance, 5000);
await post('payment', { kind: 'sales', branchId: 'central', saleId: partial.sale.id, key: 'deposit-over', amount: 5001, method: 'Tarjeta' }, 400);
const finalDeposit = await post('payment', { kind: 'sales', branchId: 'central', saleId: partial.sale.id, key: 'deposit-2', amount: 5000, method: 'Tarjeta' });
assert.equal(finalDeposit.sale.balance, 0);
assert.equal(finalDeposit.sale.status, 'Pagada');
assert.equal(finalDeposit.sale.payments.length, 3);
await post('save', { ...sale, key: 'sale-2', lines: [{ id: product, qty: 2 }] }, 400);
assert.equal((await get()).state.products[0].stock, 1);
await post('save', { ...sale, key: 'sale-3', received: -1 }, 400);
assert.equal((await get()).state.products[0].stock, 1);
const parallel = await Promise.all(['concurrent-1', 'concurrent-2'].map(key => api.POST(new Request('https://crm.test/api/crm', { method: 'POST', headers: { origin: 'https://crm.test', 'Content-Type': 'application/json' }, body: JSON.stringify({ action: 'save', data: { ...sale, key } }) }))));
assert.equal(parallel.filter(r => r.status === 200).length, 1);
assert.ok(parallel.some(r => r.status === 400 || r.status === 409));
assert.equal((await get()).state.products[0].stock, 0);
await post('save', { kind: 'appointments', branchId: 'central', patientId: patient, providerId: provider, date: '2026-10-01', time: '18:00', duration: 30, reason: 'Fuera de horario' }, 400);
await post('save', { kind: 'appointments', branchId: 'central', patientId: patient, providerId: provider, date: '2026-10-02', time: '10:00', duration: 30, reason: 'Día cerrado' }, 400);
await post('logout');
await post('login', { username: 'tech', password });
assert.equal((await get()).state.clinical[0].dp, '62');
assert.equal((await get()).state.clinical[0].age, 38);
assert.equal((await get()).state.clinical[0].lensometry,'OD -1.00');
assert.equal((await get()).state.clinical[0].followUpNotes,'Revisar adaptación');
await post('save', { kind: 'schedules', branchId: 'central', providerId: provider, type: 'date', date: '2026-10-01', available: false }, 400);
await post('save', { kind: 'schedules', branchId: 'central', providerId: provider, type: 'weekly', weekday: 4, start: '10:00', end: '12:00' }, 400);
await post('save', { kind: 'schedules', branchId: branch2, providerId: provider, type: 'weekly', weekday: 1, start: '10:00', end: '12:00' }, 403);
await post('save', { kind: 'schedules', branchId: 'central', providerId: provider, type: 'date', date: '2026-10-02', available: false });
const weekly = (await get()).state.schedules.find(s => s.type === 'weekly');
await post('delete', { kind: 'schedules', id: weekly.id }, 400);
await post('logout');
await post('login', { username: 'owner', password });
await post('user', { username: 'readonly', name: 'Solo lectura', role: 'vendedor', branches: ['central'], permissions: ['patients:read'], password });
await post('user', { username: 'tech2', name: 'Otro tecnólogo', role: 'tecnologo', branches: ['central'], permissions: model.defaults.tecnologo, password });
const tech2 = (await get()).users.find(u => u.username === 'tech2').id;
await post('save', { kind: 'schedules', branchId: 'central', providerId: tech2, type: 'weekly', weekday: 1, start: '09:00', end: '12:00' });
const otherSchedule = (await get()).state.schedules.find(s => s.providerId === tech2);
const newData = (await get()).state.clinical[0];
assert.equal(newData.patientName, 'Paciente prueba');
assert.equal(newData.previousPrescription, 'OD -0.50 / OI -0.25');
await post('save', { kind: 'reminders', branchId: 'central', appointmentId: (await get()).state.appointments[0].id }, 400);
await post('save', { kind: 'patients', ...(await get()).state.patients.find(p => p.id === patient), phone: '+56 9 1234 5678', reminderConsent: true });
const prepared = await post('save', { kind: 'reminders', branchId: 'central', appointmentId: (await get()).state.appointments[0].id });
assert.equal(prepared.reminder.status, 'Preparado');
assert.ok(prepared.reminder.url.startsWith('https://wa.me/56912345678?text='));
assert.ok(!prepared.reminder.message.includes('DATOS CLINICOS'));
await post('save', { kind: 'reminders', ...prepared.reminder, status: 'Enviado manualmente' });
assert.equal((await get()).state.reminders[0].status, 'Enviado manualmente');
const logoForm = () => { const f = new FormData(); f.append('branchId', 'central'); f.append('file', new Blob([Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a4l8AAAAASUVORK5CYII=', 'base64')], { type: 'image/png' }), 'logo.png'); return f; };
let logoResult = await logoApi.POST(new Request('https://crm.test/api/branch-logo', { method: 'POST', headers: { origin: 'https://crm.test' }, body: logoForm() }));
assert.equal(logoResult.status, 200);
assert.equal(blobs.size, 3);
assert.equal(JSON.parse(Buffer.from(blobs.get('workspace-backups/latest.json').bytes).toString()).state.branches.find(b => b.id === 'central').logoKey != null, true);
assert.ok((await get()).state.branches.find(b => b.id === 'central').logoKey);
logoResult = await logoApi.GET(new Request('https://crm.test/api/branch-logo?branchId=central'));
assert.equal(logoResult.status, 200);
assert.equal(logoResult.headers.get('content-type'), 'image/png');
logoResult = await logoApi.POST(new Request('https://crm.test/api/branch-logo', { method: 'POST', headers: { origin: 'https://crm.test' }, body: logoForm() }));
assert.equal(logoResult.status, 200);
assert.equal(blobs.size, 3);
const wrongLogo = new FormData();
wrongLogo.append('branchId', 'central');
wrongLogo.append('file', new Blob(['<svg></svg>'], { type: 'image/png' }), 'bad.png');
logoResult = await logoApi.POST(new Request('https://crm.test/api/branch-logo', { method: 'POST', headers: { origin: 'https://crm.test' }, body: wrongLogo }));
assert.equal(logoResult.status, 400);
const techAccount = (await get()).users.find(u => u.username === 'tech');
await post('user', { ...techAccount, branches: ['central', branch2] });
await post('logout');
await post('login', { username: 'tech', password });
await post('save', { kind: 'schedules', branchId: branch2, providerId: provider, type: 'weekly', weekday: 1, start: '09:00', end: '12:00' });
assert.ok((await get()).state.schedules.some(s => s.branchId === branch2));
await post('save', { kind: 'schedules', branchId: branch2, providerId: provider, type: 'weekly', weekday: 4, start: '09:30', end: '11:00' }, 400);
await post('logout');
await post('login', { username: 'readonly', password });
assert.equal((await get()).state.patients.length, 1);
await post('save', { kind: 'patients', branchId: 'central', name: 'No permitido' }, 403);
await post('delete', { kind: 'patients', id: patient }, 403);
logoResult = await logoApi.POST(new Request('https://crm.test/api/branch-logo', { method: 'POST', headers: { origin: 'https://crm.test' }, body: logoForm() }));
assert.equal(logoResult.status, 403);
await post('logout');
await post('login', { username: 'tech', password });
await post('save', { kind: 'schedules', ...otherSchedule, end: '13:00' }, 403);
await post('delete', { kind: 'schedules', id: otherSchedule.id }, 403);
await post('logout');
await post('login', { username: 'mount', password });
data = await get();
assert.equal(data.state.clinical.length, 0);
assert.equal(data.state.patients[0].rut, undefined);
assert.equal(data.state.branches.length, 2);
const job = data.state.jobs[0];
await post('save', { kind: 'movements', branchId: 'central', productId: product, delta: 3, reason: 'Reposición', key: 'in-1' });
assert.equal((await get()).state.products[0].stock, 3);
await post('save', { kind: 'movements', branchId: 'central', productId: product, delta: -1, reason: 'Material usado', jobId: job.id, key: 'out-1' });
assert.equal((await get()).state.products[0].stock, 2);
await post('save', { kind: 'movements', branchId: 'central', productId: product, delta: -1, reason: 'Material usado', jobId: job.id, key: 'out-1' });
assert.equal((await get()).state.products[0].stock, 2);
await post('save', { kind: 'movements', branchId: 'central', productId: product, delta: -3, reason: 'Sin stock', jobId: job.id, key: 'out-2' }, 400);
await post('save', { kind: 'products', ...(await get()).state.products[0], stock: 99 }, 403);
await post('save', { kind: 'jobs', ...job, status: 'En montaje', progressNote: 'Biselado completo' });
assert.equal((await get()).state.jobs[0].timeline.length, 2);
assert.equal((await get()).state.jobs[0].timeline[1].note, 'Biselado completo');
const stale = job;
await post('save', { kind: 'jobs', ...stale, status: 'Entregado' }, 409);
await post('logout');
for (let i = 0; i < 5; i++)
    await post('login', { username: 'seller', password: 'incorrect' }, 401);
await post('login', { username: 'seller', password }, 429);
platform = false;
const denied = await api.GET();
assert.equal(denied.status, 401);
console.log('PASS: setup, roles, branch isolation, clinical privacy, CSRF, booking conflicts, linked-patient protection, stock, sale idempotency, insufficient payment, lab timeline, login lockout, private identity gate, schedules, clinical fields, permissions by action, reminders, logos, stock movements and stale order protection.');
