import {env} from 'cloudflare:workers';
import {db,gate,me,scope} from '@/lib/server-auth';
import {allowed} from '@/lib/model';
function fail(message:string,status=400):never{throw Object.assign(new Error(message),{status})}
async function context(){await gate();const user=await me();if(!user)fail('Vuelve a iniciar sesión.',401);if(!env.BUCKET)fail('La carga de logos aún no está disponible.',503);const row:any=await db().prepare('SELECT * FROM workspace WHERE id=1').first();if(!row)fail('Configura el CRM.',409);return {user,row,state:JSON.parse(row.data),bucket:env.BUCKET}}
function failure(e:any){return Response.json({error:e.status?e.message:'No se pudo procesar el logo. Inténtalo nuevamente.'},{status:e.status||503,headers:{'Cache-Control':'no-store'}})}
async function snapshot(state:any,version:number,bucket:any){const now=new Date(),slot=Math.floor(now.getUTCMinutes()/15)*15,stamp=`${now.toISOString().slice(0,13)}-${String(slot).padStart(2,'0')}`,body=JSON.stringify({exportedAt:now.toISOString(),version,state});try{await Promise.all([bucket.put('workspace-backups/latest.json',body,{httpMetadata:{contentType:'application/json'}}),bucket.put(`workspace-backups/${stamp}.json`,body,{httpMetadata:{contentType:'application/json'}})])}catch(e){console.error('No se pudo guardar el respaldo automático.',e)}}
export async function GET(req:Request){try{const {user,state,bucket}=await context();const branch=state.branches.find((b:any)=>b.id===new URL(req.url).searchParams.get('branchId'));if(!branch||!scope(user,branch.id))fail('Sucursal no disponible.',403);if(!branch.logoKey)return new Response(null,{status:404});const file=await bucket.get(branch.logoKey);if(!file)return new Response(null,{status:404});return new Response(file.body,{headers:{'Content-Type':file.httpMetadata?.contentType||'application/octet-stream','Cache-Control':'private, max-age=60','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'none'; sandbox"}})}catch(e){return failure(e)}}
export async function POST(req:Request){let uploaded:string|undefined;try{if(req.headers.get('origin')!==new URL(req.url).origin)fail('Origen no válido.',403);const {user,row,state,bucket}=await context();if(!allowed(user,'branches','logo'))fail('No tienes permiso para subir logos.',403);if(Number(req.headers.get('content-length'))>2200000)fail('El logo debe pesar menos de 2 MB.');const form=await req.formData();const file=form.get('file');const branch=state.branches.find((b:any)=>b.id===form.get('branchId'));if(!branch||!scope(user,branch.id))fail('Sucursal no disponible.',403);if(!(file instanceof File)||!file.size||file.size>2097152)fail('Selecciona una imagen de hasta 2 MB.');const bytes=new Uint8Array(await file.arrayBuffer());const png=[137,80,78,71,13,10,26,10].every((x,i)=>bytes[i]===x);const jpeg=bytes[0]===255&&bytes[1]===216&&bytes[2]===255;const webp=String.fromCharCode(...bytes.slice(0,4))==='RIFF'&&String.fromCharCode(...bytes.slice(8,12))==='WEBP';const mime=png?'image/png':jpeg?'image/jpeg':webp?'image/webp':'';if(!mime||file.type!==mime)fail('Usa una imagen PNG, JPG o WebP válida.');const key='branch-logos/'+branch.id+'/'+crypto.randomUUID();await bucket.put(key,bytes,{httpMetadata:{contentType:mime}});uploaded=key;const old=branch.logoKey;branch.logoKey=key;branch.updatedAt=new Date().toISOString();state.audit.push({id:crypto.randomUUID(),date:branch.updatedAt,userId:user.id,action:'logo',kind:'branches',recordId:branch.id});const result=await db().prepare('UPDATE workspace SET data=?,version=version+1 WHERE id=1 AND version=?').bind(JSON.stringify(state),row.version).run();if(!result.meta.changes){await bucket.delete(key);uploaded=undefined;fail('La sucursal cambió. Intenta subir el logo nuevamente.',409)}await snapshot(state,row.version+1,bucket);uploaded=undefined;if(old)await bucket.delete(old).catch(()=>{});return Response.json({ok:true},{headers:{'Cache-Control':'no-store'}})}catch(e){if(uploaded&&env.BUCKET)await env.BUCKET.delete(uploaded).catch(()=>{});return failure(e)}}
